basePath: /api/v1/
host: 13.90.25.178:8082
info:
  contact:
    email: namrata.chougule@think360.ai
    name: Namrata Chougule
  description: API Registration Portal Backend
  title: FlowXpert API Registration Backend
  version: "1.0"
paths: {}
swagger: "2.0"
