basePath: /api/v1/
host: localhost:8008
info:
  contact:
    email: neil.haria@think360.ai
    name: Neil Haria
    url: https://www.swagger.io/support
  description: A service where the user can register it's own pre-built APIs to eventually
    consume in Workflow Designer & Journey Designer
  termsOfService: https://swagger.io/terms/
  title: FlowXpert API Framer
  version: "2.0"
paths: {}
swagger: "2.0"
